# Generated by Django 3.1.7 on 2021-05-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('duration', models.FloatField(max_length=200)),
                ('times_played', models.IntegerField(default=0, max_length=200)),
                ('artist', models.URLField()),
                ('album', models.URLField()),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.album')),
            ],
        ),
    ]
