# Generated by Django 3.1.7 on 2021-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='self',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='self',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='self',
            field=models.URLField(default=''),
        ),
    ]
